// <auto-generated />
namespace catastro_final.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedNamesField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedNamesField));
        
        string IMigrationMetadata.Id
        {
            get { return "201611220556395_addedNamesField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
